version: "3"
services:
  nginx:
      image: nginx:nginx1.23.3
      ports:
        - 80:80
      volumes:
        - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - /opt/nginx/html:/etc/nginx/html
        - /opt/nginx/logs:/var/log/nginx
  mysql:
    image: mysql:mysql8.0.32
    ports:
      - 7777:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql
      - /home/mysql/conf/:/etc/mysql/conf.d
      - /home/mysql/logs/:/var/log/mysql
  -redis:
    image: redis:redis7
    ports:
      - 6666:6379
    volumes:
      - /home/redis/conf/redis.conf:/etc/redis/redis.conf
      - /home/redis/data:/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
    volumes:
      - /home/luffyapi:/home
