# Generated by Django 3.2.16 on 2023-02-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='pub_date',
            new_name='publish_date',
        ),
    ]
