# Generated by Django 3.2.16 on 2023-02-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_pub_date_course_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='课时排序'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='orders',
            field=models.IntegerField(verbose_name='优先级'),
        ),
    ]
