# Generated by Django 3.2.16 on 2023-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20230203_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='课程打折价格'),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_type',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '折')], default=0, verbose_name='是否打折'),
        ),
    ]
