# Generated by Django 3.2.16 on 2023-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='jwt认证token'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='token_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='jwt认证token有效期'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['username', 'password'], name='idx_name_pwd'),
        ),
    ]
